### ISSUE TITLE
Mod Tabs Disappearing 

### ISSUE THREAD

**Issue by Necrotic-Caviar** [MSchmoecker/HammerTime#5]
After downloading the 0.1.3 update, the tabs for VALKEA, Clutter, and OdinArchitect seem to have disappeared (MoreGates still shows up). I tried messing with the .cfg file and redownloading Hammer Time and the offending mods, but nothing I could do on my end resulted in the tabs showing up again in the build menu. 

Thanks for your help, and the modding work!

**Comment by MSchmoecker** [comment]
Please post your full log here, the path is under BepInEx/LogOutput.log.
MoreGates adds the tab by itself, so I suspect there is an error that prevents HammerTime from loading.

**Comment by Necrotic-Caviar** [comment]
[LogOutput.log](https://github.com/MSchmoecker/HammerTime/files/8874130/LogOutput.log)

**Comment by MSchmoecker** [comment]
Okay, the log doesn't show any error or unusual behaviour. I've tired the three mods (VALKEA, Clutter and OdinArchitect) with HammerTime and it worked without any problem. There must be a mod conflict with this version.

Make sure to have no piece table deactivated in the config and then try to find out the conflicting mods:
- keep HammerTime, Jötunn and either VALKEA, Clutter or OdinArchitect
- remove half of the other mods, dragging them out of the plugins folder is the fastes way
- start the game, if the tab still isn't showing, one of the active mods is conflicing, otherwise one in the other half
- keep doing this until you are down to a few mods and list them here

I know this is some work but threre isn't much I can do with 100 mods loaded. By removing half of the mods every time, it doesn't take too long as with one-by-one.

**Comment by Necrotic-Caviar** [comment]
Looks like OdinPlus-ChickenBoo is the culprit, interestingly enough. Replicated with the three mods mentioned previously individually.

**Comment by MSchmoecker** [comment]
Fixed in version 0.1.4

**Comment by Necrotic-Caviar** [comment]
Awesome, thank you so much!
